FROM --platform=linux/amd64 python:3.11

RUN mkdir -p /opt/dagster/dagster_home /opt/dagster/app

COPY vortex/dagster /opt/dagster/app/

COPY ../../requirements.txt /opt/dagster/app/

RUN pip install -r requirements.txt

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

# Copy dagster instance YAML to $DAGSTER_HOME
COPY vortex/dagster/dagster.yaml /opt/dagster/dagster_home/

WORKDIR /opt/dagster/app

EXPOSE 3000

ENTRYPOINT ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
